In [4]:
from dataset import SkempiDataset
import json
from tqdm.auto import tqdm

In [5]:
skempi = SkempiDataset(csv_path = "/home/hongtan/pretrain_single/data/S2815_afterprocess.csv",
            pdb_dir = "/home/hongtan/pretrain_single/data/pdb_s2815",
            cache_dir = "/home/hongtan/pretrain_single/data/cache")

/home/hongtan/miniconda3/envs/DDAffinity/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))


In [3]:
print(skempi)


In [4]:
print(a)

{'chain_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'C', 'A', 'A', 'A', 'C', 'A', 'A', 'A', 'A', 'C', 'A', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'C', 'A', 'A', 'C', 'A', 'C', 'A', 'C', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'C', 'C', 'A', 'A', 'C', 'C', 'A', 'A', 'A', 'C', 'A', 'A', 'C', 'C', 'A', 'C', 'C', 'C', 'A', 'A', 'A', 'A', 'A', 'C', 'A', 'C', 'A', 'C', 'A', 'C', 'A', 'A', 'A', 'C'], 'chain_nb': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
        0, 0,

In [9]:
from tqdm.auto import tqdm


In [6]:
for e in tqdm(skempi):
    # 检查 e 是否为 None，并且检查 e 是否包含 'mut_flag' 键
    if e is not None and 'mut_flag' in e:
        if all(flag == False for flag in e['mut_flag']):
            # 如果全为 False，打印 e['mutations']
            print(e['mutations'])
    else:
        print("Skipping invalid entry:", e)  # 可以添加这个语句帮助调试


  0%|          | 0/2800 [00:00<?, ?it/s]

 18%|█▊        | 513/2800 [00:23<01:44, 21.96it/s]


In [5]:
a['pos_atoms'] = a['pos_heavyatom'][:, :5]
a['mask_atoms'] = a['mask_heavyatom'][:, :5]

In [6]:
print(a)

{'chain_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'], 'chain_nb': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,

In [7]:
pos_CB = _get_CB_positions(a['pos_atoms'], a['mask_atoms'])

In [8]:
print(pos_CB.shape)

torch.Size([128, 3])


In [9]:
select_flag = (a['mut_flag'] > 0)

In [10]:
print(select_flag)

tensor([ True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False])

In [11]:
pos_sel = pos_CB[select_flag]

In [12]:
import torch

In [13]:
dist_from_sel = torch.cdist(pos_CB, pos_sel)

In [14]:
print(dist_from_sel)

tensor([[2.2097e-02],
        [4.5611e+00],
        [5.1156e+00],
        [5.3309e+00],
        [5.4231e+00],
        [5.6027e+00],
        [5.7673e+00],
        [6.3070e+00],
        [6.6380e+00],
        [6.8962e+00],
        [7.0460e+00],
        [7.1454e+00],
        [7.3419e+00],
        [7.8228e+00],
        [8.8167e+00],
        [8.9365e+00],
        [9.0935e+00],
        [9.2854e+00],
        [9.4998e+00],
        [9.7455e+00],
        [9.9703e+00],
        [1.0270e+01],
        [1.0420e+01],
        [1.0566e+01],
        [1.1182e+01],
        [1.1314e+01],
        [1.1358e+01],
        [1.1437e+01],
        [1.1522e+01],
        [1.1826e+01],
        [1.1890e+01],
        [1.2434e+01],
        [1.2514e+01],
        [1.2522e+01],
        [1.2756e+01],
        [1.2792e+01],
        [1.2814e+01],
        [1.3012e+01],
        [1.3041e+01],
        [1.3330e+01],
        [1.3460e+01],
        [1.3483e+01],
        [1.3579e+01],
        [1.3858e+01],
        [1.3903e+01],
        [1

In [15]:
patch_idx = torch.argsort(dist_from_sel.view(-1))[:128]

In [16]:
print(patch_idx)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127])


In [17]:
data_patch = _index_select_data(a, patch_idx)


In [18]:
print(data_patch)

{'chain_id': ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'], 'chain_nb': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,

In [19]:
for k,v in a.items():
    print(k)
    print(v)

chain_id
['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A']
chain_nb
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0

In [20]:
b = skempi[0]
for k,v in b.items():
    print(k)
    print(v)

chain_id
['I', 'E', 'E', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'I', 'E', 'I', 'E', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'I', 'E', 'E', 'I', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'I', 'E', 'E', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'E', 'I', 'E', 'I', 'E', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'I', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'I', 'E', 'I', 'E', 'E', 'I', 'I', 'E', 'I', 'E', 'E', 'E']
chain_nb
tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0

In [21]:
pos_CB = _get_CB_positions(b['pos_atoms'], b['mask_atoms'])

In [22]:
select_flag = (b['mut_flag'] > 0)

In [23]:
pos_sel = pos_CB[select_flag]

In [24]:
dist_from_sel = torch.cdist(pos_CB, pos_sel).min(dim=1)[0]  # (L, )

In [25]:
print(dist_from_sel)

tensor([1.1049e-02, 4.1121e+00, 4.1941e+00, 5.0874e+00, 5.1459e+00, 5.1521e+00,
        5.6877e+00, 5.7503e+00, 5.8367e+00, 6.1242e+00, 6.1326e+00, 6.1989e+00,
        7.0028e+00, 7.8995e+00, 8.3241e+00, 8.3383e+00, 8.5777e+00, 8.7363e+00,
        8.7897e+00, 8.8459e+00, 8.8879e+00, 8.9422e+00, 9.1111e+00, 9.1184e+00,
        9.1674e+00, 9.2208e+00, 9.2706e+00, 9.5699e+00, 9.5765e+00, 9.7513e+00,
        9.7690e+00, 9.7699e+00, 9.8579e+00, 9.8815e+00, 9.9517e+00, 1.0080e+01,
        1.0123e+01, 1.0137e+01, 1.0676e+01, 1.0723e+01, 1.0989e+01, 1.1164e+01,
        1.1203e+01, 1.1275e+01, 1.1312e+01, 1.1373e+01, 1.1474e+01, 1.1569e+01,
        1.1589e+01, 1.1610e+01, 1.1627e+01, 1.1660e+01, 1.1772e+01, 1.1861e+01,
        1.1915e+01, 1.1953e+01, 1.2024e+01, 1.2288e+01, 1.2341e+01, 1.2503e+01,
        1.2533e+01, 1.2536e+01, 1.2547e+01, 1.2818e+01, 1.2956e+01, 1.3194e+01,
        1.3258e+01, 1.3313e+01, 1.3334e+01, 1.3414e+01, 1.3512e+01, 1.3559e+01,
        1.3588e+01, 1.3686e+01, 1.3710e+

In [26]:
patch_idx = torch.argsort(dist_from_sel.view(-1))[:128]


In [27]:
print(patch_idx)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127])


In [28]:
from dataloader import SkempiDatasetManager

In [29]:
dataloader = SkempiDatasetManager(batch_size=32,num_workers=4)


All Data: 9543 samples loaded.


In [3]:
from torch.nn import DataParallel

In [1]:
import os
import csv
import time
import json
import torch
import random
import argparse
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

from model import DDG_RDE_Network, Codebook
from trainer import CrossValidation, recursive_to
from dataloader import SkempiDatasetManager
from utils import set_seed, check_dir, eval_skempi_three_modes, save_code, load_config

from ipdb import set_trace


def pretrain(epoch, model, optimizer, dataloader):
    model.train()
    
    for batch_idx, batch in enumerate(dataloader):
        if batch is None:
            continue
        batch = recursive_to(batch, device)
        if batch is None:
            print(f"Error: Batch is None at epoch {epoch}")
            return
        _, e_q_loss, s_recon_loss, h_recon_loss, x_recon_loss = model(batch)
        loss_vae = e_q_loss * 0.005 + s_recon_loss + h_recon_loss + x_recon_loss
        print(loss_vae)
        # 继续训练逻辑
    print(f"Completed epoch {epoch}")



/home/hongtan/miniconda3/envs/DDAffinity/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
save_dir = '/home/hongtan/pretrain/weight'
param = json.loads(open("/home/hongtan/pretrain/config/param_configs.json", 'r').read())
args = argparse.Namespace(**param)
vae_model = Codebook(args).to(device)
vae_optimizer = torch.optim.Adam(vae_model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

dataloader_manager = SkempiDatasetManager(batch_size=16)

for epoch in range(1, args.pre_epoch+1):
    dataloader = dataloader_manager.get_pretrain_loader()  # 每个 epoch 获取新的 DataLoader
    pretrain(epoch, vae_model, vae_optimizer, dataloader)

for p in vae_model.parameters():
    p.requires_grad_(False)

torch.save(vae_model.state_dict(), os.path.join(save_dir, 'checkpoint', f'vae_model.ckpt'))


/home/hongtan/miniconda3/envs/DDAffinity/lib/python3.10/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))


All Data: 9543 samples loaded.
All Data: 9543 samples loaded.
tensor(4.1811, device='cuda:6', grad_fn=<AddBackward0>)
tensor(4.1918, device='cuda:6', grad_fn=<AddBackward0>)
tensor(4.1935, device='cuda:6', grad_fn=<AddBackward0>)
tensor(4.1426, device='cuda:6', grad_fn=<AddBackward0>)
tensor(4.1959, device='cuda:6', grad_fn=<AddBackward0>)


OutOfMemoryError: CUDA out of memory. Tried to allocate 1.88 GiB. GPU 6 has a total capacity of 23.69 GiB of which 1.35 GiB is free. Including non-PyTorch memory, this process has 22.32 GiB memory in use. Of the allocated memory 18.25 GiB is allocated by PyTorch, and 3.77 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [11]:
import os
import copy
import math
import random
import pickle
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

import torch
from torch.utils.data import Dataset

from Bio.PDB.PDBParser import PDBParser
from Bio.PDB.Polypeptide import one_to_index, index_to_one
from common_utils.transforms import get_transform
from common_utils.protein.parsers import parse_biopython_structure
import json
from ipdb import set_trace

In [16]:
parser = PDBParser(QUIET=True)
pdb_path = '/home/hongtan/pretrain_single/data/pdb_s2815/1lrp.pdb'
model = parser.get_structure(None, pdb_path)[0]
data, seq_map = parse_biopython_structure(model)

In [13]:
print(data)

None


In [ ]:
1LRP,A,Q44Y,-0.02
1LRP,A,Y22H,-2.25
1LRP,A,I84S,-2.25
1LRP,A,Q33Y,1.32
1LRP,A,G46A,0.66
1LRP,A,G48A,0.87
1LRP,A,G48S,0.68
1LRP,A,G48N,0.79
1LRP,A,K4Q,0.43
1LRP,A,A66T,-2.99
1LRP,A,Y88C,2.4
1LRP,A,A49V,-1.22

In [2]:
from common_utils.transforms._base import _index_select_data, register_transform, _get_CB_positions


In [8]:
for e in skempi:
    print(e['aa'])


tensor([16,  3,  2,  5,  8, 15,  7,  5,  0,  7, 19, 13,  7, 14,  0,  0,  9,  3,
         8, 15, 18,  2,  9,  0,  4,  9,  5,  2, 11,  8,  0, 14,  5, 12, 14, 15,
        16, 19, 17, 15, 19, 18,  7, 16,  9, 17,  5, 11,  7, 15,  9, 17, 15, 14,
        19,  7, 12, 17,  7, 11,  2,  6, 19,  0,  5, 11, 19, 15,  2, 11,  4,  2,
         5, 16,  7,  6, 11, 15, 14,  8, 15, 16,  8, 15, 15, 14, 18,  6,  0, 19,
         8,  9, 14,  5,  8, 18,  4, 16,  5, 18,  9,  5, 13,  2,  4,  2,  5, 16,
        16, 19, 15,  4, 16,  2, 14,  3,  7, 11,  8, 15,  5,  9,  2,  9, 13,  5,
         2, 19])
tensor([ 0, 13,  9,  3, 15,  5,  0, 18, 15,  7,  2, 17, 16,  8,  0,  5,  6, 17,
        14,  8, 18,  9, 16,  7, 15,  0, 11, 15,  2,  8,  2,  5, 19,  5,  8, 12,
         8, 15,  9, 14, 19,  5,  0, 15,  5,  2, 19,  9, 18, 11, 14, 13,  7,  2,
         7,  5,  9,  0, 19,  5, 16,  5, 12,  9,  7,  3, 14, 14, 15,  4,  4, 12,
        11,  8,  9,  9, 19,  2, 17,  4, 11,  3, 16,  0, 15,  0, 16, 19, 14, 15,
         5, 11, 19,  7,

KeyboardInterrupt: 

In [9]:
import pandas as pd

# 读取CSV数据
data = pd.read_csv('/home/hongtan/pretrain_single/data/modified_file.csv')

# 创建一个列表，用于保存突变前后氨基酸一致的行
same_mutations = []

# 遍历每一行数据
for index, row in data.iterrows():
    # 获取突变前的氨基酸和突变后的氨基酸
    mutation = row['corrected mutations']
    wt_aa = mutation[0]  # 突变前的氨基酸
    mt_aa = mutation[-1]  # 突变后的氨基酸
    
    # 检查突变前后的氨基酸是否相同
    if wt_aa == mt_aa:
        same_mutations.append(row)

# 将结果转换为 DataFrame 以便查看
same_mutations_df = pd.DataFrame(same_mutations)

# 输出结果
if not same_mutations_df.empty:
    print("突变前后氨基酸一致的行：")
    print(same_mutations_df)
else:
    print("没有突变前后氨基酸一致的行。")


没有突变前后氨基酸一致的行。
